### ISSUE TITLE
Error on inconsistent issue data

### ISSUE THREAD

**Issue by v-orlando** [sw-group/ghbe#2] opened 2024-06-06 12:27 UTC
### Description
When trying to retrieve issues you get inconsistent data

### Step
1. run the service
2. open the swagger api from this url:
3. run the GET issues
4. See the result

### Expected result
repo: 'owner/name'; created_at: 'YYYY-MM-DDTHH:MM:ss'; updated_at: 'YYYY-MM-DDTHH:MM:ss'; closed_at: 'YYYY-MM-DDTHH:MM:ss' (only if the state is closed)

### Current result
repo: none; created_at: none; updated_at: none; closed_at: none

**Comment by s-dimaria** [comment] 2024-06-06 12:29
The issue is fixed by the pull request.

**Closed as completed by s-dimaria** 2024-06-06 12:29 UTC
